language: chsarp
solution: TestExerciceConverter
mono: none
dotnet: 2.0.0
dist: trusty
script:
- dotnet restore
- dotnet test ./UnitTests/UnitTests.csproj
- dotnet build -c Release
- dotnet publish -c Release -o ./Converter/publish
deploy:
    on:
        tags: true